//
// Created by mahee on 2019-03-11.
//

#ifndef HUFFMAN_PROJECT_CMPT225_FREQUENCYCOUNTER_H
#define HUFFMAN_PROJECT_CMPT225_FREQUENCYCOUNTER_H


class frequencyCounter {

};


#endif //HUFFMAN_PROJECT_CMPT225_FREQUENCYCOUNTER_H
